### ISSUE TITLE
Add mesh antenna to Xenons

### ISSUE THREAD

**Issue by caseywdunn** [dunnlab/equipment_monitor#3]
Here is the suggested antenna:

https://store.particle.io/collections/accessories/products/wi-fi-or-mesh-2-4ghz-antenna

Needs to be enabled in software specifically for xenons:

https://community.particle.io/t/xenon-mesh-external-antenna-enable/51424

**Comment by caseywdunn** [comment]
Can also add antenna to borons. Could place it on left side of top acrylic plate, where it would be as far as possible from the cell antenna.

https://docs.particle.io/datasheets/cellular/boron-datasheet/

**Comment by brevans** [comment]
Ahhh, they use the same chip / antenna for BLE and mesh. Sneaky devils only label the antenna "BT" on the board.

**Comment by caseywdunn** [comment]
Antennas installed on all devices. Software not yet configured. They did loose then reestablish connectivity when I attached the antenna in most cases. Makes me wonder if they can autodetect antenna.

**Comment by caseywdunn** [comment]
Created branch for this issue - https://github.com/dunnlab/equipment_monitor/tree/issue-3

**Comment by caseywdunn** [comment]
Enabling system threading is required to change antennas - https://docs.particle.io/reference/device-os/firmware/photon/#system-thread
